# Generated by Django 5.2.4 on 2025-08-26 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='travelOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travelType', models.CharField(choices=[('TRAIN', 'Train'), ('FLIGHT', 'Flight'), ('BUS', 'Bus')], default='TRAIN', max_length=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateTime', models.DateTimeField()),
                ('availableSeats', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='app.city')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='app.city')),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfSeats', models.IntegerField()),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bookingDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('travelOption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.traveloptions')),
            ],
        ),
    ]
